apiVersion: apps/v1
kind: Deployment
metadata:
  name: ingress2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ingress2
  template:
    metadata:
      labels:
        app: ingress2
    spec:
      containers:
      - name: ingress2
        image: httpd
        ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: ingress2-service
spec:
  type: NodePort
  selector:
    app: ingress2
  ports:
    - port: 80
      targetPort: 80
