version: '3.8'

services:
  prenom-service:
    build:
      context: ./prenomService
      dockerfile: Dockerfile
    container_name: prenom-service
    ports:
      - "8080:80"  
    environment:
      - SPRING_APPLICATION_NAME=prenom-service
      - SERVER_PORT=8080
    networks:
      - ingnum-network
    restart: unless-stopped

  rental-service:
    build:
      context: ./RentalService
      dockerfile: Dockerfile
    container_name: rental-service
    ports:
      - "8081:8081"
    environment:
      - SPRING_APPLICATION_NAME=rental-service
      - SERVER_PORT=8081
      - CUSTOMER_SERVICE_URL=http://prenom-service:80
    networks:
      - ingnum-network
    depends_on:
      - prenom-service
    restart: unless-stopped

networks:
  ingnum-network:
    driver: bridge